@startwbs
* MainWindow
** MenuBar 
'Ez itt nem külön objektum, közös interfész?
*** InitView
*** SnowplowPlayerView
*** SnowplowView
*** BusPlayerView
*** EndView
** Map
*** FieldView
**** VehicleView
**** BuildingView
**** SaltStoneView
*** Arrow
*** CrossRoadView

@endwbs