@startuml

participant "Tesztelő" as tester
participant "start: Field" as startField
participant "next: Field" as next
participant "c1: Car" as c1
participant "c2: Car" as c2
participant "pd: PlayerDriver" as pd

tester -> pd: new()
pd --> tester: pd
tester -> c1: new(pd)
c1 --> tester: c1
tester -> c2: new(null)
c2 --> tester: c2
tester -> startField: setVehicle(c1)
startField --> tester: 
'Le tudjam rakni az előttem levő mezőre a második kocsit
tester -> startField: getForward()
startField --> tester: next 
'itt a next-ről nem tudom hogy Field, csak azt hogy IRoad
'IRoad Field.getForward()
tester -> next: getAvailable()
'List<IField> Field.getAvailable()
next --> tester: [next]
tester -> next: setVehicle(c2)
next --> tester:


/' tesztelő meghívja Vehicle.step()-et
'/
tester -> c1: step()
'void SnowPlow.contact(Vehicle v)'
'  


c1 --> tester:
@enduml