participant "bp: BusPlayer"
participant "b: Bus"

participant "s1: Station"
participant "s2: Station"
participant "field: Field"

"field: Field" -> "b: Bus" :interact(field)

"b: Bus" -> "s1: Station": getPair()
"s1: Station" --> "b: Bus": s2
"b: Bus" -> "bp: BusPlayer": give(1)
"bp: BusPlayer" --> "b: Bus"
"b: Bus" --> "field: Field"