participant "spp: SnowPlowPlayer"
participant "sp: SnowPlow"

participant "h: Brush"
participant "field: Field"
participant "i: Inventory"

"field: Field" -> "sp: SnowPlow" :interact(field)
"sp: SnowPlow" -> "h: Brush": interact(field, i)
"h: Brush" --> "sp: SnowPlow": true

"sp: SnowPlow" -> "spp: SnowPlowPlayer": give(1)

"spp: SnowPlowPlayer" --> "sp: SnowPlow"
"spp: SnowPlowPlayer" --> "field: Field"


