@startuml melt

participant "Controller" as controller
participant "f: Field" as field
participant "s: Salt" as salt
participant "snow: Snow" as beforeMelt
participant "layer: Layer" as afterMelt

controller -> field: melt()
field -> salt: melt(snow)
salt --> field: layer
field --> controller


@enduml