@startuml buyFromShop

participant "p: SnowPlowPlayer" as player
participant "sp: SnowPlow" as sp
participant "shop: Shop" as shop
participant "vehicles: List<SnowPlow>" as vehicleList

player -> shop: buy(player, sp, 1)
shop -> sp: price()
sp --> shop: 5
shop -> player: charge(5)
player --> shop: true
shop -> sp: apply(player, 1)
sp -> player: addVehicle(sp)
player --> sp
sp --> shop
shop --> player

@enduml