@startuml buyFromShop

participant "sp: SnowPlow" as sp
participant "p: SnowPlowPlayer" as player
participant "head: DragonHead" as item
participant "i: Inventory" as inventory
participant "shop: Shop" as shop
player -> shop: buy(player, head, 1)
shop -> item: price()
item --> shop: 3
shop -> player: charge(3)
player --> shop: true
shop -> item: apply(player, 1)

item -> player: snowplow()
player --> item: sp
item -> sp: getInventory()
sp --> item: i
item -> inventory: addItem(head, 1)
inventory --> item:
item --> shop:
shop --> player:

@enduml