@startuml buyFromShopNoMoney

participant "sp: SnowPlow" as sp
participant "p: SnowPlowPlayer" as player
participant "head: DragonHead" as item
participant "i: Inventory" as inventory
participant "shop: Shop" as shop
player -> shop: buy(player, head, 1)
shop -> head: price()
head --> shop: 3
shop -> player: charge(3)
player --> shop: false
shop --> player:

@enduml