participant "i: Inventory"
participant "current: Field"
participant "sp: SnowPlow"
participant "h: SaltSpreader"
participant "s: Salt"

"sp: SnowPlow" -> "h: SaltSpreader" : interact(current, i)
"h: SaltSpreader" -> "i: Inventory": removeItem(s,1)
"i: Inventory" --> "h: SaltSpreader": True
"h: SaltSpreader" -> "current: Field": setSalt(s)
"current: Field" --> "h: SaltSpreader"
"h: SaltSpreader" --> "sp: SnowPlow"
