@startuml

actor "user" as user
participant "sppv: SnowPlowPlayer View" as sppv
participant "map: Map" as map
participant "controller: SnowPlowPlayerController" as controller
participant "snowplow: snowplow" as 1
participant "field: Field" as field1

user -> sppv: click "Select SnowPlow button"
sppv -> controller: info()
controller --> sppv: player
... dialog: select snowplow ...
sppv -> controller: select(snowplowSerial)
... redirect to snowplow view ...
controller --> sppv:
sppv --> user:

@enduml