class InitView{
    + map: IMap
    + controller: InitController

    
    + handleAddField(Point point): void
    + handleSetFrontFieldField(int f1, int f2): void
    + handleSetFrontFieldCrossRoad(int f1, int f2): void
    + handleSetFrontCrossRoadField(int f1, int f2): void
    + handleAddCrossRoad(Point point): void
    + handleAddSnowplowPlayer(): void
    + handleAddBusPlayer(): void
    + handleAddStations(int f1, int f2): void
    + handleAddHome(int f1): void
    + handleAddOffice(int f1): void
    + handlePlaceSnowplow(int f1): void
    + handlePlaceBus(int f1): void
    + handleSetRound(): void
    + handleSetSide(int f1, int f2): void
    + handleSetSnowing(): void
    + handleStart(): void
}


