class SnowplowPlayerView{
    + SnowPlowController snowPlowController
    + SnowPlowPlayerController snowPlowPlayerController
    + SnowplowView snowplowView

    + handleSelect(int sp1): void
    + handleBuySnowplow(): void
    + handleInfo(): void
    + handleStepAll(): void
    + handleAddMoney(int money): void
}