class SnowplowView{
    + SnowPlowController snowPlowController

    + handleInfo(): void
    + handleBuy(): void
    + handleShop(): void
    + handleBack(): void
    + handleSetNext(int f1): void
    + handleSwitchHead(int h1): void
}