@startuml
left to right direction

skinparam linetype ortho

       interface IInventoryItem{
           + key(): string
           + limit(): int
       }


       interface IHead implements IInventoryItem{
           + interact(field: IField, inventory: Inventory): bool
       }



 class Broom implements IHead, ShopItem
    {
    +key(): string
    +interact(field: IField, inventory: Inventory): bool
    +price(): int
    +apply(ctx: PurchaseContext, amount: int): void
    + limit(): int
    }
    
    class Brush implements IHead, ShopItem
    {
    +key(): string
    +interact(field: IField, inventory: Inventory): bool
    +price(): int
    +apply(ctx: PurchaseContext, amount: int): void
    + limit(): int
    }
    
    class SaltSpreader implements IHead, ShopItem
    {
    +key(): string
    +interact(field: IField, inventory: Inventory): bool
    +price(): int
    +apply(ctx: PurchaseContext, amount: int): void
    + limit(): int
    }
    
    class IceBreaker implements IHead, ShopItem
    {
    +key(): string
    +interact(field: IField, inventory: Inventory): bool
    +price(): int
    +apply(ctx: PurchaseContext, amount: int): void
    + limit(): int
    }
    
    class Dragon implements IHead, ShopItem
    {
    +key(): string
    +interact(field: IField, inventory: Inventory): bool
    +price(): int
    +apply(ctx: PurchaseContext, amount: int): void
    + limit(): int
    }

    class StoneSplasher implements IHead, ShopItem
    {
    +key(): string
    +interact(field: IField, inventory: Inventory): bool
    +price(): int
    +apply(ctx: PurchaseContext, amount: int): void
    + limit(): int
    }


class Biokerosene implements IInventoryItem, ShopItem
    {
    +key(): string
    +price(): int
    +apply(ctx: PurchaseContext, amount: int): void
    + limit(): int
    }

class Stone implements IInventoryItem, ShopItem
    {
    +key(): string
    +price(): int
    +apply(ctx: PurchaseContext, amount: int): void
    + limit(): int
    }

   interface ShopItem{
       + price(): int
       + apply(ctx: PurchaseContext, amount: int): void
   }
@enduml