@startuml

actor "user" as user
participant "view: SnowplowView" as view
participant "controller: SnowplowController" as controller

user -> view: click "Shop" button
view -> controller: shop()
controller --> view: shopItems
... dialog: List of shopItems ...
view --> user:


@enduml