@startuml
start
if(SnowPlowPlayers.isEmpty) then (no)
    repeat
    :get SnowPlowPlayers[i];
    :subscribe to SnowPlowPlayers[i];
        repeat
        :get SnowPlowPlayer[i].SnowPlows[d];
        :Subscribe to snowPlow;
        :Subscribe to snowPlow.Inventory;
        :Subscribe to snowPlow.Driver;
        repeat while (More SnowPlows?) is (yes d++) not (no)
    repeat while (more SnowPlowPlayers?) is (yes i++) not (no)
endif
stop
@enduml