@startuml StepCarBFS

actor "Tesztelő" as tester
participant "c1: Car" as car
participant "d1: CarDriver" as driver
participant "o1: Office" as dest
participant "f1: Field" as f1
participant "f2: Field" as f2
participant "fn: Field" as fn

tester -> car: step()
activate car
car -> car: canMove()
activate car
'Skeleton.askInt("Meddig van még lerobbanva?")'
car --> car: üzemképes
deactivate car
alt üzemképes
    car -> driver: nextMove()
    activate driver

    driver -> dest: getField()
    activate dest
    dest --> driver: f2
    deactivate dest

    note right of driver
      cameFrom.put(f1, null)
      queue.add(f1)
    end note

    loop while !queue.isEmpty()
        driver -> fn: getFront()
        activate fn
        fn --> driver: IRoad
        deactivate fn
        driver -> fn: getAvailable()
        activate fn
        fn --> driver: List<IField>
        deactivate fn
        driver -> fn: getRight()
        activate fn
        fn --> driver: IField
        deactivate fn

        alt neighbor == target
            note right of driver
              break outer
              cameFrom tartalmazza a teljes utat
            end note
        else neighbor új
            note right of driver
              cameFrom.put(neighbor, node)
              queue.add(neighbor)
            end note
        end
    end

    alt target nem elérhető
        driver --> car: next (változatlan)
    else útvonal visszakövetése
        loop cameFrom.get(step) != f1
            note right of driver
              step = cameFrom.get(step)
            end note
        end
        driver --> car: f2
    end
    deactivate driver

    car -> driver: getCurrent()
    activate driver
    driver --> car: f1
    deactivate driver
    car -> f1: tryExit(f2)
    activate f1
    f1 --> car:
    deactivate f1
end
car --> tester:
deactivate car

@enduml