@startuml

/'komm diagramba szukseges: ket ures mezo sima layer'/
/'CarEnterCollision'/
/'hatso auto probal kilepni a mezobol es karambolozik az elotte levo autoval'/
title CarEnterCollision
participant "Tesztelő" as tester
participant "pre: Prerequisite" as pre
participant "start:Field" as startField
participant "next: Field" as nextField
participant "c1: Car" as c1
participant "c2: Car" as c2
participant "cd: CarDriver" as cd
participant "l1: Layer" as startLayer
/'letrehoz egy cardrivert'/
tester->cd:new()
cd-->tester:cd

/'letrehozza az elso autot a cardriverrel'/
tester->c1:new(cd)
c1-->tester:c1

/'letrehozza a masodik autot aminek nincs vezetoje mert nem mozdul'/
tester->c2:new(null)
c2-->tester:c2

/'a pre visszaadja a kezdo fieldet'/
tester->pre: CarEnterCollision()
pre-->tester:startField

/'az elso mezo beallitja az elso autot'/
tester->startField: setVehicle(c1)
startField-->tester:

/'megkerdezi az elso mezot hogy mi a kovetkezo IRoad'/
tester->startField: getForward()
startField-->tester:next

/'elkeri a Field-ek listajat a kovetkezo IRoad-tol'/
tester->nextField:getAvailable()
nextField-->tester: [next]

/'beallitja a masodik mezore a masodik autot'/
tester->nextField: setVehicle(c2)
nextField-->tester:

tester->c1: step()

/'jatekos beallitja h elore szeretne lepni'/
c1->cd: nextMove()
cd-->c1:next

/'lekerdezi az auto aktualis mezojet'/
c1 -> cd: getCurrent()
cd --> c1: startField

/'elso auto megprobal kilepni'/
c1 -> startField: tryExit(next)

/'elso auto megkerdezi h kilephet-e'/
startField -> startLayer: canExit(c1)
startLayer --> startField: true

/'elso auto megprobal belepni'/
startField -> nextField: tryEnter(c1)

/'hatso auto osszetorik'/
nextField -> c1: contact(c2)
c1 --> nextField: 

/'a elso auto is osszetorik'/
nextField -> c2: contact(c1)
c2 --> nextField:

/'tryEnter-re a valasz, tehat nem lephet be a c1'/
nextField --> startField: false

/'tryExit-re a valasz, tehat nem lephet ki a c1'/
startField --> c1:

/'step()-re a valasz'/
c1 --> tester:


/'megegyszer megprobal lepni, de sikertelenul'/
tester->c1: step()
c1-->tester:

@enduml