@startuml
start
if(SnowPlowPlayers.isEmpty) then (no)
    repeat
    :get SnowPlowPlayers[i];
    :subscribe to SnowPlowPlayers[i];
        repeat
        :get SnowPlowPlayer.SnowPlows[i];
        :Subscribe to snowPlow;
        :Subscribe to snowPlow.Inventory;
        :Subscribe to snowPlow.Driver;
        repeat while (More SnowPlows?)
    repeat while (more SnowPlowPlayers?) is (yes i++) not (no)
endif
stop
@enduml