@startuml
participant "Controller" as controller order 10
participant "c: Car" as car order 30
participant "driver: CarDriver" as driver order 20
participant "next: Field" as next order 60
participant "current: Field" as current order 40
participant "s1: Snow" as currentLayer order 50

controller -> car: step()
car -> driver: nextMove()
driver --> car: next
car -> driver: getCurrent()
driver --> car: current
car -> current: tryExit(next)
current -> currentLayer: canExit(c)
currentLayer --> current: false
current --> car:
car --> controller:
@enduml