@startuml StepSnowplowFromSnow

actor "Tesztelő" as tester
participant "s5: Snowplow" as snowplow
participant "p1: SnowPlowPlayer" as player
participant "ib: IceBreaker" as head
participant "i: Inventory" as inventory
participant "d5: PlayerDriver" as driver
participant "f8: Field" as f8
participant "l8: Ice" as l8
participant "f9: Field" as f9
participant "l9: Ice" as l9
participant "slip: IceSlipVisitor" as iceslipvisitor
participant "r: Random" as r
participant "breakIce: IceBreakerClearLayerVisitor" as breakIceVisitor

tester -> snowplow: step()
activate snowplow
snowplow -> snowplow: canMove()
activate snowplow
snowplow --> snowplow: true
deactivate snowplow
snowplow -> driver: nextMove()
activate driver
driver --> snowplow: f9
deactivate driver
snowplow -> driver: getCurrent()
activate driver
driver --> snowplow: f8
deactivate driver
snowplow -> f8: tryExit(f9)
activate f8
f8 -> l8: canExit(s5)
activate l8
l8 --> f8: true
deactivate l8

f8 -> f9: tryEnter(s5)
activate f9

f9 -> l9: enter()
activate l9
l9 --> f9: l9
deactivate l9

f9 -> l9: slip(s5, r)
activate l9
l9 -> iceslipvisitor: <<create>>(r)
activate iceslipvisitor
iceslipvisitor --> l9:
deactivate iceslipvisitor
l9 -> iceslipvisitor: visit(s5)
activate iceslipvisitor
iceslipvisitor --> l9: 
deactivate iceslipvisitor
l9 -> iceslipvisitor: getResult()
activate iceslipvisitor
iceslipvisitor --> l9: false
deactivate iceslipvisitor
l9 --> f9: false
deactivate l9

f9 -> snowplow: interact(f9)
activate snowplow

snowplow -> head: interact(f9, i)
activate head
head -> f9: getLayer()
activate f9
f9 --> head: l9
deactivate f9
head -> breakIceVisitor: <<create>>()
activate breakIceVisitor
breakIceVisitor --> head:
deactivate breakIceVisitor
head -> breakIceVisitor: visit(l9)
activate breakIceVisitor
note right
Mivel itt be kell billenteni a flaget, ezért ezt itt meg fogjuk tenni
a visitoron belül
end note
breakIceVisitor -> l9: setBroken(true)
activate l9
l9 --> breakIceVisitor:
deactivate l9
breakIceVisitor --> head:
deactivate breakIceVisitor
head -> breakIceVisitor: getResult()
activate breakIceVisitor
breakIceVisitor --> head: true
deactivate breakIceVisitor
head --> snowplow: true
deactivate head
snowplow -> player: give(1)
activate player
player --> snowplow:
deactivate player

snowplow --> f9: 
deactivate snowplow

f9 --> f8: true
deactivate f9

f8 --> snowplow:
deactivate f8

snowplow --> tester: 
deactivate snowplow
