@startuml

actor "user" as user
participant "init: InitView" as init

participant "controller: InitController" as controller


user -> init: click "Set Rounds button"
init -> map: waitForField(handleAddHome)
   ... dialog: index...
map --> init: handleAddHome(index)
init -> controller: addBusPlayer()
controller --> init:
init --> user:

@enduml