@startuml

actor "user" as user
participant "sppv: SnowPlowPlayer View" as sppv
participant "controller: SnowPlowPlayerController" as controller
participant "field: Field" as 1

user -> sppv: click "BuySp button"
sppv -> controller: buySnowplow()
controller -> 1: <<set for field>>
1 --> controller: snowplow

controller --> sppv:

... observer is notified, updates the vehicle UI ...

sppv --> user:


@enduml