@startuml

actor "user" as user
participant "sppv: SnowPlowPlayer View" as sppv
participant "controller: SnowPlowPlayerController" as controller

user -> sppv: click "SnowplowPlayer Info button"
sppv -> controller: info()
controller --> sppv:
sppv --> user:

@enduml