@startuml

actor "user" as user
participant "bpv: BusPlayer View" as sppv
participant "map: Map" as map
participant "controller: BusPlayerController" as controller


user -> sppv: click "BusPlayer Step button"
sppv -> map: waitForField(handleSetNext)
   ... click field ...
map --> sppv: handleSetNext(index)
sppv -> controller: setNext(index)

controller --> sppv:

sppv --> user:


@enduml