@startuml buyFromShop

actor "Tesztelő" as tester
participant "p: SnowPlowPlayer" as player
participant "sp: SnowPlow" as sp
participant "s: Shop" as shop


tester -> shop: buy(player, sp, 1)
activate shop
shop -> sp: price()
activate sp
'Skeleton.askInt("Mennyibe kerül?")
sp --> shop: price
deactivate sp
shop -> player: charge(5)
activate player
'Skeleton.askInt("Mennyi pénze van?")
player --> shop: success
deactivate player
alt success
shop -> sp: apply(player, 1)
activate sp
sp -> player: addVehicle(sp)
activate player
player --> sp
deactivate player
sp --> shop:
deactivate sp
end
shop --> tester
deactivate shop
@enduml